# Generated by Django 4.1.11 on 2023-10-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="strip_checkout_session_id",
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
